# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FPGA_DEMO/dsp/dsp.srcs/sources_1/ip/xbip_dsp48_macro_2/xbip_dsp48_macro_2.xci
# IP: The module: 'xbip_dsp48_macro_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_DEMO/dsp/dsp.srcs/sources_1/ip/xbip_dsp48_macro_2/xbip_dsp48_macro_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xbip_dsp48_macro_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/FPGA_DEMO/dsp/dsp.srcs/sources_1/ip/xbip_dsp48_macro_2/xbip_dsp48_macro_2.xci
# IP: The module: 'xbip_dsp48_macro_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_DEMO/dsp/dsp.srcs/sources_1/ip/xbip_dsp48_macro_2/xbip_dsp48_macro_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xbip_dsp48_macro_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
