set_property PACKAGE_PIN T22 [get_ports m_axi_error_0]
set_property IOSTANDARD LVCMOS33 [get_ports m_axi_error_0]
set_property IOSTANDARD LVCMOS33 [get_ports m_axi_init_axi_txn_0]
set_property PACKAGE_PIN T18 [get_ports m_axi_init_axi_txn_0]
set_property PACKAGE_PIN T21 [get_ports m_axi_txn_done_0]
set_property IOSTANDARD LVCMOS33 [get_ports m_axi_txn_done_0]
