set_property PACKAGE_PIN F22 [get_ports {sw_tri_io[0]}]
set_property PACKAGE_PIN G22 [get_ports {sw_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_tri_io[0]}]
set_property PACKAGE_PIN T21 [get_ports {led_tri_io[1]}]
set_property PACKAGE_PIN T22 [get_ports {led_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_tri_io[0]}]
